### ISSUE TITLE
README有一点描述错误，导致程序运行有些问题

### ISSUE THREAD

**Issue by lqz123** [Ray0089/PSGMN#1]
在README文档的###Testing on the linemod描述为
1. Download the pretrained model of `cat` and put it to `$ROOT/model/cat/200.pth`.

实际上代码中导入预训练模型的代码为：
`  pretrained_model = torch.load(os.path.join(model_dir, "{}.pkl".format(pth)))`

所以后缀应该是pkl文件

**Comment by Ray0089** [comment]
已经更正，谢谢关注

**Comment by doublechenchen** [comment]
> 
方便问一下您三哪个版本的pytorch运行，cuda用的哪个版本python用的哪个版本？ 我运行python setup.py build_ext --inplace   一直报错
